/**
 * Dashboard persistence schemas — Template files (+ the legacy shape).
 *
 * TARGET MODEL (approved dashboard-template rework, model 1A): the persisted
 * shape under `STORAGE_KEYS.dashboards` is
 * `{ templates: DashboardTemplate[], activeId: string, activeRoomId: string | null }`.
 * A {@link DashboardTemplate} is one complete presentation/layout profile for
 * the SAME physical smart home: it owns an ordered list of
 * {@link TemplateRoom} references. A `TemplateRoom` references a PHYSICAL
 * room id (owned by the devices module — never cloned) and owns that
 * Template's widget layout for the room. A physical room may be referenced by
 * many Templates; widgets keep their `roomId` mirror field so the existing
 * room-scoped binding authority/uniqueness keep working (the nesting is the
 * authority; `widget.roomId` must equal the enclosing reference's `roomId` —
 * enforced by the dashboard service).
 *
 * `activeId` selects the active Template; `activeRoomId` is the narrow
 * History compatibility seam (the shared physical-room selection used by the
 * History tab) — the Settings stack's management navigation never derives
 * from it.
 *
 * LEGACY MIGRATION (deterministic, idempotent, non-destructive): files stored
 * by the predecessor shape `{ dashboards: LegacyDashboard[], activeId,
 * activeRoomId }` are parsed by {@link LegacyDashboardsFileSchema} and
 * structurally migrated by {@link migrateLegacyDashboardsFile}: each legacy
 * dashboard becomes a Template; widgets group by concrete physical `roomId`
 * preserving first-seen order; roomless (global) widgets are folded into the
 * FIRST reference so no widget placement is ever dropped; widget ids,
 * bindings, titles, layouts and unknown custom fields survive EXACTLY
 * (the widget schema preserves unknown top-level fields). The service then
 * stamps `updatedAt` and re-orders references by the devices registry order.
 * Already-migrated files parse directly and never migrate again (idempotent).
 */

import { z } from 'zod';

import { WidgetConfigSchema } from '@modules/widgets/api';

/**
 * One ordered physical-room reference inside one Template: the referenced
 * PHYSICAL room id (devices-module identity — shared, never cloned), the
 * reference's position inside the Template, and the Template's widget layout
 * for that room.
 */
export const TemplateRoomSchema = z.object({
  /** Referenced physical room id (must exist in the devices registry). */
  roomId: z.string().min(1, 'Template room reference is required'),
  /** Zero-based position of the room inside the Template (stable order). */
  order: z.number().int('Room order must be an integer').min(0),
  /** The Template's widget layout for this room (validated individually). */
  widgets: z.array(WidgetConfigSchema),
});

/** One ordered physical-room reference inside one Template. */
export type TemplateRoom = z.infer<typeof TemplateRoomSchema>;

/**
 * One Dashboard Template: a complete presentation/layout profile over the
 * shared physical home. `updatedAt` records the latest successful
 * Template-owned mutation (metadata, membership/order, widget-layout save) —
 * never live MQTT readings and never a shared physical-room rename.
 */
export const DashboardTemplateSchema = z.object({
  /** Stable Template id (generated by the service on create). */
  id: z.string().min(1, 'Template id is required'),
  /** Display name (e.g. 'Trang chủ'). */
  name: z.string().trim().min(1, 'Template name is required'),
  /** Latest successful Template-owned mutation (epoch millis). */
  updatedAt: z
    .number()
    .int('updatedAt must be an integer')
    .nonnegative('updatedAt must be non-negative'),
  /** Ordered physical-room references (a room at most once per Template). */
  rooms: z.array(TemplateRoomSchema),
});

/** One Dashboard Template. */
export type DashboardTemplate = z.infer<typeof DashboardTemplateSchema>;

/** The persisted dashboards file: all Templates + selections. */
export const DashboardsFileSchema = z
  .object({
    templates: z.array(DashboardTemplateSchema),
    activeId: z.string().min(1, 'Active template id is required'),
    /**
     * History compatibility seam: the shared physical-room selection used by
     * the History tab (`null` = none). The Settings management stack and the
     * view-only Dashboard surface never read it.
     */
    activeRoomId: z.string().min(1).nullable().default(null),
  })
  .superRefine((file, ctx) => {
    const templateIds = new Set<string>();
    for (const template of file.templates) {
      if (templateIds.has(template.id)) {
        ctx.addIssue({
          code: 'custom',
          path: ['templates'],
          message: `Duplicate template id "${template.id}"`,
        });
      }
      templateIds.add(template.id);
      const roomIds = new Set<string>();
      const widgetIds = new Set<string>();
      for (const room of template.rooms) {
        if (roomIds.has(room.roomId)) {
          ctx.addIssue({
            code: 'custom',
            path: ['templates'],
            message: `Template "${template.id}" references room "${room.roomId}" more than once`,
          });
        }
        roomIds.add(room.roomId);
        for (const widget of room.widgets) {
          if (widgetIds.has(widget.id)) {
            ctx.addIssue({
              code: 'custom',
              path: ['templates'],
              message: `Template "${template.id}" has duplicate widget id "${widget.id}"`,
            });
          }
          widgetIds.add(widget.id);
          if (widget.roomId !== room.roomId) {
            ctx.addIssue({
              code: 'custom',
              path: ['templates'],
              message: `Widget "${widget.id}" roomId "${String(
                widget.roomId,
              )}" does not match its room reference "${room.roomId}"`,
            });
          }
        }
      }
    }
    if (!templateIds.has(file.activeId)) {
      ctx.addIssue({
        code: 'custom',
        path: ['activeId'],
        message: `Active template "${file.activeId}" does not exist`,
      });
    }
  });

/** The persisted dashboards file shape (current). */
export type DashboardsFile = z.infer<typeof DashboardsFileSchema>;

/**
 * LEGACY persistence shape (pre-Template): one dashboard with a flat widget
 * list, the active dashboard id and the shared active room filter.
 */
export const LegacyDashboardSchema = z.object({
  /** Stable dashboard id (generated by the service on create). */
  id: z.string().min(1, 'Dashboard id is required'),
  /** Display name (e.g. 'Trang chủ'). */
  name: z.string().trim().min(1, 'Dashboard name is required'),
  /** Widgets on this dashboard (validated individually, unknown fields kept). */
  widgets: z.array(WidgetConfigSchema),
});

/** One legacy dashboard (id, name, widgets). */
export type LegacyDashboard = z.infer<typeof LegacyDashboardSchema>;

/** The legacy dashboards file shape (pre-Template). */
export const LegacyDashboardsFileSchema = z
  .object({
    dashboards: z.array(LegacyDashboardSchema),
    activeId: z.string().min(1, 'Active dashboard id is required'),
    activeRoomId: z.string().min(1).nullable().default(null),
  })
  .superRefine((file, ctx) => {
    const ids = new Set<string>();
    for (const dashboard of file.dashboards) {
      if (ids.has(dashboard.id)) {
        ctx.addIssue({
          code: 'custom',
          path: ['dashboards'],
          message: `Duplicate dashboard id "${dashboard.id}"`,
        });
      }
      ids.add(dashboard.id);
      const widgetIds = new Set<string>();
      for (const widget of dashboard.widgets) {
        if (widgetIds.has(widget.id)) {
          ctx.addIssue({
            code: 'custom',
            path: ['dashboards'],
            message: `Dashboard "${dashboard.id}" has duplicate widget id "${widget.id}"`,
          });
        }
        widgetIds.add(widget.id);
      }
    }
    if (!ids.has(file.activeId)) {
      ctx.addIssue({
        code: 'custom',
        path: ['activeId'],
        message: `Active dashboard "${file.activeId}" does not exist`,
      });
    }
  });

/** The legacy dashboards file shape (pre-Template). */
export type LegacyDashboardsFile = z.infer<typeof LegacyDashboardsFileSchema>;

/**
 * Reserved room id for the structural migration of a legacy dashboard whose
 * widgets are ALL roomless (global). The dashboard SERVICE finalizes this
 * sentinel against the devices registry on load: with at least one physical
 * room the reference is retargeted to the FIRST registry room (merged into
 * the existing reference when the Template already references it — the
 * widgets adopt the host roomId so the mirror invariant holds); when no
 * physical room exists at all the reference is kept so no widget is ever
 * dropped, and the retarget self-heals on a later load once a room exists.
 */
export const MIGRATION_GLOBAL_ROOM_ID = '__global__';

/**
 * Structural legacy → Template migration (pure, registry-independent).
 *
 * For every legacy dashboard:
 * 1. Widgets are bucketed by their concrete `roomId`; roomless widgets form
 *    the global bucket (sentinel {@link MIGRATION_GLOBAL_ROOM_ID}).
 * 2. Buckets become ordered room references in FIRST-SEEN order; the global
 *    bucket is folded into the FIRST reference (appended last in that room)
 *    so no placement is dropped. A dashboard with only roomless widgets gets
 *    one reference under the sentinel id.
 * 3. Widget order/ids/bindings/titles/layouts/unknown fields are preserved
 *    EXACTLY (already guaranteed by the loose widget schema).
 * 4. `updatedAt` is stamped `0`; the dashboard service sets the real
 *    timestamp at migration commit time (Clock-injected).
 *
 * The same input always produces the same output; an already-migrated file
 * never enters this function (the repository discriminates by shape).
 */
export function migrateLegacyDashboardsFile(
  legacy: LegacyDashboardsFile,
): DashboardsFile {
  const templates: DashboardTemplate[] = legacy.dashboards.map(dashboard => {
    const globalBucket: WidgetConfigForBucket[] = [];
    const buckets = new Map<string, WidgetConfigForBucket[]>();
    for (const widget of dashboard.widgets) {
      const key = widget.roomId ?? MIGRATION_GLOBAL_ROOM_ID;
      if (key === MIGRATION_GLOBAL_ROOM_ID) {
        globalBucket.push(widget);
        continue;
      }
      const bucket = buckets.get(key);
      if (bucket) {
        bucket.push(widget);
      } else {
        buckets.set(key, [widget]);
      }
    }
    const rooms: TemplateRoom[] = [...buckets.entries()].map(
      ([roomId, widgets], index) => ({
        roomId,
        order: index,
        widgets: [...widgets],
      }),
    );
    if (globalBucket.length > 0) {
      if (rooms.length > 0) {
        // Fold roomless placements into the first reference (append last —
        // deterministic, never reorders the host room's own widgets). The
        // folded widgets adopt the host reference's roomId so the widget
        // mirror field always matches its enclosing reference.
        const host = rooms[0]!;
        rooms[0] = {
          ...host,
          widgets: [
            ...host.widgets,
            ...globalBucket.map(widget => ({ ...widget, roomId: host.roomId })),
          ],
        };
      } else {
        rooms.push({
          roomId: MIGRATION_GLOBAL_ROOM_ID,
          order: 0,
          widgets: globalBucket.map(widget => ({
            ...widget,
            roomId: MIGRATION_GLOBAL_ROOM_ID,
          })),
        });
      }
    }
    return {
      id: dashboard.id,
      name: dashboard.name,
      updatedAt: 0,
      rooms,
    };
  });
  return {
    templates,
    activeId: legacy.activeId,
    activeRoomId: legacy.activeRoomId ?? null,
  };
}

/** Widget shape used while bucketing (identical to the persisted widget). */
type WidgetConfigForBucket = LegacyDashboard['widgets'][number];

/**
 * Validate arbitrary input against the CURRENT (Template) file schema.
 * Returns the parsed file or a list of human-readable field errors.
 */
export function parseCurrentDashboardsFile(
  input: unknown,
): { ok: true; value: DashboardsFile } | { ok: false; errors: string[] } {
  const result = DashboardsFileSchema.safeParse(input);
  if (result.success) {
    return { ok: true, value: result.data };
  }
  return {
    ok: false,
    errors: result.error.issues.map(
      issue => `${issue.path.join('.') || 'file'}: ${issue.message}`,
    ),
  };
}

/**
 * Validate arbitrary input against the LEGACY file schema.
 * Returns the parsed file or a list of human-readable field errors.
 */
export function parseLegacyDashboardsFile(
  input: unknown,
): { ok: true; value: LegacyDashboardsFile } | { ok: false; errors: string[] } {
  const result = LegacyDashboardsFileSchema.safeParse(input);
  if (result.success) {
    return { ok: true, value: result.data };
  }
  return {
    ok: false,
    errors: result.error.issues.map(
      issue => `${issue.path.join('.') || 'file'}: ${issue.message}`,
    ),
  };
}

/**
 * Discriminated parse used by the repository: recognizes the CURRENT
 * Template shape, the LEGACY shape (→ structurally migrated, `migrated:
 * true`) — or fails. Shape detection is by the discriminating key
 * (`templates` vs `dashboards`) so a legacy file is never "repaired" into
 * the wrong model and a malformed file is reported, never guessed.
 */
export type ParsedDashboardsFile =
  | { ok: true; value: DashboardsFile; migrated: boolean }
  | { ok: false; errors: string[] };

export function parseDashboardsFile(input: unknown): ParsedDashboardsFile {
  if (typeof input === 'object' && input !== null && 'templates' in input) {
    const current = parseCurrentDashboardsFile(input);
    return current.ok
      ? { ok: true, value: current.value, migrated: false }
      : current;
  }
  const legacy = parseLegacyDashboardsFile(input);
  if (legacy.ok) {
    return {
      ok: true,
      value: migrateLegacyDashboardsFile(legacy.value),
      migrated: true,
    };
  }
  return legacy;
}
