/**
 * Dashboard persistence schemas — one dashboard + a file of dashboards.
 *
 * The persisted shape is `{ dashboards: Dashboard[], activeId: string }` under
 * `STORAGE_KEYS.dashboards`. A `Dashboard` wraps an id, a name and a list of
 * {@link WidgetConfig} (validated by the shared widgets schema so no invalid
 * widget can ever be persisted).
 */

import { z } from 'zod';

import { WidgetConfigSchema } from '@modules/widgets/api';

/** One dashboard: id, name + its widgets. */
export const DashboardSchema = z.object({
  /** Stable dashboard id (generated by the service on create). */
  id: z.string().min(1, 'Dashboard id is required'),
  /** Display name (e.g. 'Trang chủ'). */
  name: z.string().trim().min(1, 'Dashboard name is required'),
  /** Widgets on this dashboard (validated individually). */
  widgets: z.array(WidgetConfigSchema),
});

/** A dashboard (id, name, widgets). */
export type Dashboard = z.infer<typeof DashboardSchema>;

/** The persisted dashboards file: all dashboards + the active one. */
export const DashboardsFileSchema = z
  .object({
    dashboards: z.array(DashboardSchema),
    activeId: z.string().min(1, 'Active dashboard id is required'),
    /**
     * Active room filter; `null` = "Tất cả" (show every widget). Files
     * persisted before rooms existed default to `null` (no filtering).
     */
    activeRoomId: z.string().min(1).nullable().default(null),
  })
  .superRefine((file, ctx) => {
    const ids = new Set<string>();
    for (const dashboard of file.dashboards) {
      if (ids.has(dashboard.id)) {
        ctx.addIssue({
          code: 'custom',
          path: ['dashboards'],
          message: `Duplicate dashboard id "${dashboard.id}"`,
        });
      }
      ids.add(dashboard.id);
    }
    if (!ids.has(file.activeId)) {
      ctx.addIssue({
        code: 'custom',
        path: ['activeId'],
        message: `Active dashboard "${file.activeId}" does not exist`,
      });
    }
  });

/** The persisted dashboards file shape. */
export type DashboardsFile = z.infer<typeof DashboardsFileSchema>;

/**
 * Validate arbitrary input against the dashboards file schema.
 * Returns the parsed file or a list of human-readable field errors.
 */
export function parseDashboardsFile(
  input: unknown,
): { ok: true; value: DashboardsFile } | { ok: false; errors: string[] } {
  const result = DashboardsFileSchema.safeParse(input);
  if (result.success) {
    return { ok: true, value: result.data };
  }
  return {
    ok: false,
    errors: result.error.issues.map(
      issue => `${issue.path.join('.') || 'file'}: ${issue.message}`,
    ),
  };
}
