/**
 * Device registry service — CRUD for rooms + devices.
 *
 * Owns the current {@link DevicesSnapshot} in memory (loaded from the
 * repository, seeded on first run). Every mutation:
 *
 * 1. validates with the zod schemas (including the binding↔capability
 *    constraint),
 * 2. persists through the repository,
 * 3. updates the in-memory snapshot and mirror store,
 * 4. publishes `devices:changed` with the ids removed in the mutation.
 *
 * Failures are returned as {@link Result} — nothing is applied on error.
 */

import type { EventBus } from '@core/eventbus';
import { err, Errors, ok, type AppError, type Result } from '@core/errors';
import type { Logger } from '@core/logger';
import type { Clock } from '@core/time';

import type {
  CapabilityDef,
  Device,
  DevicesSnapshot,
  Room,
} from '../domain/devices';
import {
  CapabilityDefSchema,
  CapabilityMachineKeySchema,
  DeviceSchema,
  RoomSchema,
} from '../domain/devices';
import { seedDevices } from '../domain/seeds';
import type { DevicesRepository } from '../data/devicesRepository';
import type { DevicesStore } from '../ui/devicesStore';
import { createDevicesStore } from '../ui/devicesStore';

/** Input for creating a device (id is generated by the registry). */
export interface NewDeviceInput {
  readonly name: string;
  readonly roomId?: string;
  readonly type: string;
  readonly capabilities: readonly string[];
  readonly binding:
    | {
        readonly kind: 'telemetry-sensor';
      }
    | {
        readonly kind: 'relay';
        readonly index: 1 | 2 | 3;
      };
}

/** Input for adding a capability to the catalog (`type` required + unique). */
export type NewCapabilityInput = Omit<CapabilityDef, 'type'> & {
  readonly type: string;
};

/** Partial patch for updating a capability definition (type is immutable). */
export interface CapabilityPatch {
  readonly label?: string;
  readonly kind?: 'sensor' | 'switch';
  readonly unit?: string;
  readonly color?: string;
  readonly icon?: string;
}

/** Partial patch for updating a room (fields are merged over the current). */
export interface RoomPatch {
  readonly name?: string;
  readonly order?: number;
  readonly icon?: string;
}

/**
 * What happens to a removed room's devices + widgets (CP5 migration dialog).
 *
 * - `move`: devices (and their widgets) move to `roomId`.
 * - `unassign`: devices become roomless; widgets become global.
 */
export type RoomMigrationTarget =
  | { readonly kind: 'move'; readonly roomId: string }
  | { readonly kind: 'unassign' };

/** Partial patch for updating a device (fields merged over the current). */
export interface DevicePatch {
  readonly name?: string;
  readonly roomId?: string;
  readonly type?: string;
  readonly capabilities?: readonly string[];
  readonly binding?: Device['binding'];
}

/**
 * Default {@link DeviceRegistryService} implementation.
 */
export class DeviceRegistryServiceImpl {
  private readonly repository: DevicesRepository;
  private readonly bus: EventBus;
  private readonly logger: Logger;
  private readonly clock: Clock;
  private snapshot: DevicesSnapshot;
  private readonly store: DevicesStore;
  private idCounter = 0;
  private readonly isCapabilityInUse?: (type: string) => boolean;
  private readonly migrateWidgetsFromRoom?: (
    fromId: string,
    toId: string | null,
  ) => Promise<Result<void>>;

  constructor(options: {
    repository: DevicesRepository;
    bus: EventBus;
    logger: Logger;
    clock: Clock;
    /**
     * Optional predicate: is a capability type still bound by any widget?
     * Wired by the composition root (dashboard bindings); when it returns
     * true, `removeCapability` is rejected.
     */
    isCapabilityInUse?: (type: string) => boolean;
    /**
     * Optional applier (CP5): move / globalize the dashboard widgets that
     * belong to a removed room. Wired to the dashboard service at the
     * composition root; when absent, widget room ids are left untouched.
     */
    migrateWidgetsFromRoom?: (
      fromId: string,
      toId: string | null,
    ) => Promise<Result<void>>;
  }) {
    this.repository = options.repository;
    this.bus = options.bus;
    this.logger = options.logger;
    this.clock = options.clock;
    this.isCapabilityInUse = options.isCapabilityInUse;
    this.migrateWidgetsFromRoom = options.migrateWidgetsFromRoom;
    this.snapshot = seedDevices();
    this.store = createDevicesStore(this.snapshot);
  }

  /** The zustand store mirrored to the UI (subscribe for re-renders). */
  getStore(): DevicesStore {
    return this.store;
  }

  /** Load the persisted snapshot (seeds defaults on first run). */
  async load(): Promise<Result<void>> {
    const result = await this.repository.load();
    if (!result.ok) {
      return result;
    }
    this.snapshot = result.value;
    this.store.getState().setSnapshot(this.snapshot);
    this.logger.info(
      `Devices: loaded ${result.value.devices.length} devices / ${result.value.rooms.length} rooms`,
    );
    return ok(undefined);
  }

  /** All registered devices. */
  getDevices(): readonly Device[] {
    return this.snapshot.devices;
  }

  /** All rooms. */
  getRooms(): readonly Room[] {
    return this.snapshot.rooms;
  }

  /** The capability catalog (built-ins + user-defined). */
  getCapabilities(): readonly CapabilityDef[] {
    return this.snapshot.capabilities;
  }

  /** Find a device by id (undefined when unknown). */
  findDevice(id: string): Device | undefined {
    return this.snapshot.devices.find(device => device.id === id);
  }

  /** Add a capability definition to the catalog (`type` must be unique). */
  async addCapability(input: NewCapabilityInput): Promise<Result<void>> {
    // CP-R4: strict ASCII machine-key validation for NEW capabilities.
    // Legacy persisted keys (e.g. Vietnamese slugs) are accepted by
    // CapabilityDefSchema for read compatibility, but new creation must
    // use the strict format.
    const keyResult = CapabilityMachineKeySchema.safeParse(input.type);
    if (!keyResult.success) {
      return err(
        Errors.validation(
          'Invalid capability key',
          keyResult.error.issues.map(i => i.message),
        ),
      );
    }
    const validated = CapabilityDefSchema.safeParse(input);
    if (!validated.success) {
      return err(
        Errors.validation(
          'Invalid capability',
          validated.error.issues.map(i => i.message),
        ),
      );
    }
    if (this.getCapabilities().some(def => def.type === validated.data.type)) {
      return err(
        Errors.validation(
          `Capability type "${validated.data.type}" already exists`,
        ),
      );
    }
    return this.commit({
      ...this.snapshot,
      capabilities: [...this.getCapabilities(), validated.data],
    });
  }

  /** Update a capability definition (patch; the type key is immutable). */
  async updateCapability(
    type: string,
    patch: CapabilityPatch,
  ): Promise<Result<void>> {
    const existing = this.getCapabilities().find(def => def.type === type);
    if (!existing) {
      return err(Errors.notFound(`Capability "${type}" does not exist`));
    }
    const validated = CapabilityDefSchema.safeParse({ ...existing, ...patch });
    if (!validated.success) {
      return err(
        Errors.validation(
          'Invalid capability',
          validated.error.issues.map(i => i.message),
        ),
      );
    }
    return this.commit({
      ...this.snapshot,
      capabilities: this.getCapabilities().map(def =>
        def.type === type ? validated.data : def,
      ),
    });
  }

  /**
   * Remove a capability definition from the catalog.
   *
   * Rejected with a validation error when the capability is a locked
   * built-in, when any device still declares the capability, or when the
   * injected `isCapabilityInUse` predicate (widget bindings, wired at the
   * composition root) reports it in use.
   */
  async removeCapability(type: string): Promise<Result<void>> {
    const def = this.getCapabilities().find(
      candidate => candidate.type === type,
    );
    if (!def) {
      return err(Errors.notFound(`Capability "${type}" does not exist`));
    }
    if (def.builtin) {
      return err(
        Errors.validation(
          `Capability "${type}" is built-in and cannot be removed`,
        ),
      );
    }
    if (
      this.snapshot.devices.some(device => device.capabilities.includes(type))
    ) {
      return err(
        Errors.validation(
          `Capability "${type}" is still declared by at least one device`,
        ),
      );
    }
    if (this.isCapabilityInUse && this.isCapabilityInUse(type)) {
      return err(
        Errors.validation(
          `Capability "${type}" is still bound by at least one widget`,
        ),
      );
    }
    return this.commit({
      ...this.snapshot,
      capabilities: this.getCapabilities().filter(def => def.type !== type),
    });
  }

  /** Add a room. */
  async addRoom(name: string): Promise<Result<void>> {
    const room: Room = {
      id: this.nextId('room'),
      name,
      order: this.snapshot.rooms.length,
    };
    const validated = RoomSchema.safeParse(room);
    if (!validated.success) {
      return err(
        Errors.validation(
          'Invalid room',
          validated.error.issues.map(i => i.message),
        ),
      );
    }
    return this.commit({
      ...this.snapshot,
      rooms: [...this.snapshot.rooms, validated.data],
    });
  }

  /** Update a room (name/order); id must exist. */
  async updateRoom(id: string, patch: RoomPatch): Promise<Result<void>> {
    const existing = this.snapshot.rooms.find(room => room.id === id);
    if (!existing) {
      return err(Errors.notFound(`Room "${id}" does not exist`));
    }
    const validated = RoomSchema.safeParse({ ...existing, ...patch });
    if (!validated.success) {
      return err(
        Errors.validation(
          'Invalid room',
          validated.error.issues.map(i => i.message),
        ),
      );
    }
    return this.commit({
      ...this.snapshot,
      rooms: this.snapshot.rooms.map(room =>
        room.id === id ? validated.data : room,
      ),
    });
  }

  /**
   * Remove a room with an explicit device migration (CP5).
   *
   * - `move`: the room's devices move to `target.roomId` (must exist and
   *   differ from the removed room); widgets bound to the removed room move
   *   to the target room too.
   * - `unassign`: the devices become roomless; widgets bound to the removed
   *   room become global (their roomId is dropped).
   *
   * The mutation is two-phase (registry commit, then widget migration via
   * the injected dashboard callback). When the second phase fails, the
   * registry performs a **compensating rollback**: the pre-mutation
   * snapshot is restored (repository persist + mirror store + broadcast),
   * and the returned error carries BOTH the migration failure and the
   * rollback outcome — a partial mutation is never reported as success.
   */
  async removeRoomWithMigration(
    id: string,
    target: RoomMigrationTarget,
  ): Promise<Result<void>> {
    if (!this.snapshot.rooms.some(room => room.id === id)) {
      return err(Errors.notFound(`Room "${id}" does not exist`));
    }
    if (target.kind === 'move') {
      if (target.roomId === id) {
        return err(Errors.validation('Cannot move a room into itself'));
      }
      if (!this.snapshot.rooms.some(room => room.id === target.roomId)) {
        return err(Errors.notFound(`Room "${target.roomId}" does not exist`));
      }
    }
    const previousSnapshot = this.snapshot;
    const next: DevicesSnapshot = {
      rooms: this.snapshot.rooms.filter(room => room.id !== id),
      devices: this.snapshot.devices.map(device => {
        if (device.roomId !== id) {
          return device;
        }
        return target.kind === 'move'
          ? { ...device, roomId: target.roomId }
          : { ...device, roomId: undefined };
      }),
      capabilities: this.snapshot.capabilities,
    };
    const committed = await this.commit(next);
    if (!committed.ok) {
      return committed;
    }
    if (this.migrateWidgetsFromRoom) {
      const migrated = await this.migrateWidgetsFromRoom(
        id,
        target.kind === 'move' ? target.roomId : null,
      );
      if (!migrated.ok) {
        // Compensating rollback (fix cycle 1): restore the pre-mutation
        // registry state. The mirror store is restored even when the
        // rollback persist fails, so the UI keeps showing the original
        // snapshot; the error surfaces both failure details.
        const restored = await this.commit(previousSnapshot);
        if (!restored.ok) {
          this.snapshot = previousSnapshot;
          this.store.getState().setSnapshot(previousSnapshot);
          return err(
            Errors.unknown(
              `Widget migration failed (${migrated.error.message}); registry rollback failed (${restored.error.message}) — the registry was restored in memory only`,
            ),
          );
        }
        return err(
          Errors.unknown(
            `Widget migration failed; registry rolled back (${migrated.error.message})`,
          ),
        );
      }
    }
    return ok(undefined);
  }

  /** Add a device (id generated; validated against the binding constraint). */
  async addDevice(input: NewDeviceInput): Promise<Result<void>> {
    const candidate: Device = {
      id: this.nextId('dev'),
      name: input.name,
      roomId: input.roomId,
      type: input.type,
      capabilities: [...input.capabilities],
      binding: { ...input.binding },
    };
    const validated = DeviceSchema.safeParse(candidate);
    if (!validated.success) {
      return err(
        Errors.validation(
          'Invalid device',
          validated.error.issues.map(i => `${i.path.join('.')}: ${i.message}`),
        ),
      );
    }
    if (this.snapshot.devices.some(device => device.id === validated.data.id)) {
      return err(
        Errors.validation(`Duplicate device id "${validated.data.id}"`),
      );
    }
    const catalogError = this.validateCapabilitiesForBinding(
      validated.data.capabilities,
      validated.data.binding.kind,
    );
    if (catalogError !== null) {
      return err(catalogError);
    }
    return this.commit({
      ...this.snapshot,
      devices: [...this.snapshot.devices, validated.data],
    });
  }

  /** Update a device (partial patch; id must exist). */
  async updateDevice(id: string, patch: DevicePatch): Promise<Result<void>> {
    const existing = this.snapshot.devices.find(device => device.id === id);
    if (!existing) {
      return err(Errors.notFound(`Device "${id}" does not exist`));
    }
    const validated = DeviceSchema.safeParse({ ...existing, ...patch });
    if (!validated.success) {
      return err(
        Errors.validation(
          'Invalid device',
          validated.error.issues.map(i => `${i.path.join('.')}: ${i.message}`),
        ),
      );
    }
    const catalogError = this.validateCapabilitiesForBinding(
      validated.data.capabilities,
      validated.data.binding.kind,
    );
    if (catalogError !== null) {
      return err(catalogError);
    }
    return this.commit({
      ...this.snapshot,
      devices: this.snapshot.devices.map(device =>
        device.id === id ? validated.data : device,
      ),
    });
  }

  /** Remove a device; emits `devices:changed { removedDeviceIds: [id] }`. */
  async removeDevice(id: string): Promise<Result<void>> {
    if (!this.snapshot.devices.some(device => device.id === id)) {
      return err(Errors.notFound(`Device "${id}" does not exist`));
    }
    const next: DevicesSnapshot = {
      ...this.snapshot,
      devices: this.snapshot.devices.filter(device => device.id !== id),
    };
    return this.commit(next, [id]);
  }

  /** Validate + persist a snapshot, then apply + broadcast. */
  private async commit(
    next: DevicesSnapshot,
    removedDeviceIds: readonly string[] = [],
  ): Promise<Result<void>> {
    const saved = await this.repository.save(next);
    if (!saved.ok) {
      return saved;
    }
    this.snapshot = next;
    this.store.getState().setSnapshot(next);
    this.logger.info(
      `Devices: committed ${next.devices.length} devices / ${next.rooms.length} rooms`,
    );
    this.bus.emit('devices:changed', {
      removedDeviceIds: [...removedDeviceIds],
    });
    return ok(undefined);
  }

  /**
   * Catalog membership enforcement (fix cycle 1): every declared capability
   * must exist in the current catalog AND its `kind` must match the device
   * binding (`sensor` kinds for a telemetry-sensor binding, `switch` kinds
   * for a relay binding). Unknown capability types are rejected instead of
   * silently accepted by the permissive string schema.
   */
  private validateCapabilitiesForBinding(
    capabilities: readonly string[],
    bindingKind: 'telemetry-sensor' | 'relay',
  ): AppError | null {
    const catalog = new Map(
      this.getCapabilities().map(def => [def.type, def] as const),
    );
    const expectedKind = bindingKind === 'relay' ? 'switch' : 'sensor';
    for (const type of capabilities) {
      const def = catalog.get(type);
      if (!def) {
        return Errors.validation(
          `Capability "${type}" is not defined in the capability catalog`,
        );
      }
      if (def.kind !== expectedKind) {
        return Errors.validation(
          `Capability "${type}" is a ${def.kind} capability and does not match a ${bindingKind} binding`,
        );
      }
    }
    return null;
  }

  /** Generate a stable, unique id: `<prefix>-<time>-<counter>`. */
  private nextId(prefix: 'dev' | 'room'): string {
    this.idCounter += 1;
    return `${prefix}-${this.clock.nowMillis()}-${this.idCounter}`;
  }
}
